[tool.poetry]
name = "asyncio-gevent"
version = "0.1.0"
description = ""
authors = ["Frédérique Mittelstaedt <hi@gfm.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
gevent = "*"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
black = "^21.5b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
